default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: redirect_api_development

test:
  <<: *default
  database: redirect_api_test

production:
  <<: *default
  host: hetzner3.pixelhobby.com
  database: redirect_api_production
  username: postgres
  password: postgres
